name: matex_dart
version: 0.7.2
description: Set of Forex calculators.
homepage: https://github.com/tyrcord/matex_dart
issue_tracker: https://github.com/tyrcord/matex_dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.5.0
  equatable: ^2.0.0
  meta: ^1.3.0
  decimal: ^1.1.0
  intl: ^0.17.0
  tstore_dart: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.5
  dart_code_metrics: ^3.2.2

flutter:
  assets:
    - assets/meta/
