name: matex_dart
version: 0.8.6
description: Set of Forex calculators.
homepage: https://github.com/tyrcord/matex_dart
issue_tracker: https://github.com/tyrcord/matex_dart/issues

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2
  equatable: ^2.0.3
  meta: ^1.7.0
  decimal: ^1.5.0
  intl: ^0.17.0
  tstore_dart: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.19.5
  dart_code_metrics: ^4.10.1

flutter:
  assets:
    - assets/meta/
