name: matex_dart
version: 0.1.0
author: Tyrcord Inc. <dev@tyrcord.com>
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  async: ^2.4.0

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.9.4
  rxdart: ^0.22.6
  meta: ^1.1.8
  decimal: ^0.3.5
