name: matex_dart
version: 0.1.0
author: Tyrcord, Inc. <dev@tyrcord.com>
environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.2
  equatable: ^1.2.5
  meta: ^1.1.8
  decimal: ^0.3.5
  intl: ^0.16.1
  tstore_dart: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  test: ^1.9.4

flutter:
  assets:
    - assets/meta/
