name: matex_dart
version: 0.3.0
description: Set of Forex calculators.
homepage: https://github.com/tyrcord/matex_dart
issue_tracker: https://github.com/tyrcord/matex_dart/issues

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.2
  equatable: ^1.2.5
  meta: ^1.2.4
  decimal: ^0.3.5
  intl: ^0.16.1
  tstore_dart: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  test: ^1.15.7
  dart_code_metrics: ^2.3.1

flutter:
  assets:
    - assets/meta/
