name: matex_dart
version: 0.8.4
description: Set of Forex calculators.
homepage: https://github.com/tyrcord/matex_dart
issue_tracker: https://github.com/tyrcord/matex_dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.6.1
  equatable: ^2.0.3
  meta: ^1.3.0
  decimal: ^1.2.0
  intl: ^0.17.0
  tstore_dart: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.16.8
  dart_code_metrics: ^4.0.1

flutter:
  assets:
    - assets/meta/
